package connectors

import models.RepoContents

object Responses {
    val userResponse: String =
        """{
          |  "login": "Aashvin",
          |  "id": 55795472,
          |  "node_id": "MDQ6VXNlcjU1Nzk1NDcy",
          |  "avatar_url": "https://avatars.githubusercontent.com/u/55795472?v=4",
          |  "gravatar_id": "",
          |  "url": "https://api.github.com/users/Aashvin",
          |  "html_url": "https://github.com/Aashvin",
          |  "followers_url": "https://api.github.com/users/Aashvin/followers",
          |  "following_url": "https://api.github.com/users/Aashvin/following{/other_user}",
          |  "gists_url": "https://api.github.com/users/Aashvin/gists{/gist_id}",
          |  "starred_url": "https://api.github.com/users/Aashvin/starred{/owner}{/repo}",
          |  "subscriptions_url": "https://api.github.com/users/Aashvin/subscriptions",
          |  "organizations_url": "https://api.github.com/users/Aashvin/orgs",
          |  "repos_url": "https://api.github.com/users/Aashvin/repos",
          |  "events_url": "https://api.github.com/users/Aashvin/events{/privacy}",
          |  "received_events_url": "https://api.github.com/users/Aashvin/received_events",
          |  "type": "User",
          |  "site_admin": false,
          |  "name": "Aashvin Relwani",
          |  "company": null,
          |  "blog": "",
          |  "location": null,
          |  "email": null,
          |  "hireable": null,
          |  "bio": null,
          |  "twitter_username": null,
          |  "public_repos": 11,
          |  "public_gists": 0,
          |  "followers": 2,
          |  "following": 2,
          |  "created_at": "2019-09-25T12:57:18Z",
          |  "updated_at": "2023-09-11T16:58:24Z"
          |}""".stripMargin

    val repoResponse: String =
        """[
          |  {
          |    "id": 410007962,
          |    "node_id": "R_kgDOGHA5mg",
          |    "name": "AutoFAQ-Website-Link",
          |    "full_name": "Aashvin/AutoFAQ-Website-Link",
          |    "private": false,
          |    "owner": {
          |      "login": "Aashvin",
          |      "id": 55795472,
          |      "node_id": "MDQ6VXNlcjU1Nzk1NDcy",
          |      "avatar_url": "https://avatars.githubusercontent.com/u/55795472?v=4",
          |      "gravatar_id": "",
          |      "url": "https://api.github.com/users/Aashvin",
          |      "html_url": "https://github.com/Aashvin",
          |      "followers_url": "https://api.github.com/users/Aashvin/followers",
          |      "following_url": "https://api.github.com/users/Aashvin/following{/other_user}",
          |      "gists_url": "https://api.github.com/users/Aashvin/gists{/gist_id}",
          |      "starred_url": "https://api.github.com/users/Aashvin/starred{/owner}{/repo}",
          |      "subscriptions_url": "https://api.github.com/users/Aashvin/subscriptions",
          |      "organizations_url": "https://api.github.com/users/Aashvin/orgs",
          |      "repos_url": "https://api.github.com/users/Aashvin/repos",
          |      "events_url": "https://api.github.com/users/Aashvin/events{/privacy}",
          |      "received_events_url": "https://api.github.com/users/Aashvin/received_events",
          |      "type": "User",
          |      "site_admin": false
          |    },
          |    "html_url": "https://github.com/Aashvin/AutoFAQ-Website-Link",
          |    "description": null,
          |    "fork": false,
          |    "url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link",
          |    "forks_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/forks",
          |    "keys_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/keys{/key_id}",
          |    "collaborators_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/collaborators{/collaborator}",
          |    "teams_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/teams",
          |    "hooks_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/hooks",
          |    "issue_events_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/issues/events{/number}",
          |    "events_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/events",
          |    "assignees_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/assignees{/user}",
          |    "branches_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/branches{/branch}",
          |    "tags_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/tags",
          |    "blobs_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/git/blobs{/sha}",
          |    "git_tags_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/git/tags{/sha}",
          |    "git_refs_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/git/refs{/sha}",
          |    "trees_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/git/trees{/sha}",
          |    "statuses_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/statuses/{sha}",
          |    "languages_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/languages",
          |    "stargazers_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/stargazers",
          |    "contributors_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/contributors",
          |    "subscribers_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/subscribers",
          |    "subscription_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/subscription",
          |    "commits_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/commits{/sha}",
          |    "git_commits_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/git/commits{/sha}",
          |    "comments_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/comments{/number}",
          |    "issue_comment_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/issues/comments{/number}",
          |    "contents_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/contents/{+path}",
          |    "compare_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/compare/{base}...{head}",
          |    "merges_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/merges",
          |    "archive_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/{archive_format}{/ref}",
          |    "downloads_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/downloads",
          |    "issues_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/issues{/number}",
          |    "pulls_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/pulls{/number}",
          |    "milestones_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/milestones{/number}",
          |    "notifications_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/notifications{?since,all,participating}",
          |    "labels_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/labels{/name}",
          |    "releases_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/releases{/id}",
          |    "deployments_url": "https://api.github.com/repos/Aashvin/AutoFAQ-Website-Link/deployments",
          |    "created_at": "2021-09-24T15:10:17Z",
          |    "updated_at": "2021-09-24T15:10:51Z",
          |    "pushed_at": "2021-09-24T15:10:49Z",
          |    "git_url": "git://github.com/Aashvin/AutoFAQ-Website-Link.git",
          |    "ssh_url": "git@github.com:Aashvin/AutoFAQ-Website-Link.git",
          |    "clone_url": "https://github.com/Aashvin/AutoFAQ-Website-Link.git",
          |    "svn_url": "https://github.com/Aashvin/AutoFAQ-Website-Link",
          |    "homepage": null,
          |    "size": 1,
          |    "stargazers_count": 0,
          |    "watchers_count": 0,
          |    "language": null,
          |    "has_issues": true,
          |    "has_projects": true,
          |    "has_downloads": true,
          |    "has_wiki": true,
          |    "has_pages": false,
          |    "has_discussions": false,
          |    "forks_count": 0,
          |    "mirror_url": null,
          |    "archived": false,
          |    "disabled": false,
          |    "open_issues_count": 0,
          |    "license": null,
          |    "allow_forking": true,
          |    "is_template": false,
          |    "web_commit_signoff_required": false,
          |    "topics": [
          |
          |    ],
          |    "visibility": "public",
          |    "forks": 0,
          |    "open_issues": 0,
          |    "watchers": 0,
          |    "default_branch": "main"
          |  },
          |  {
          |    "id": 454023362,
          |    "node_id": "R_kgDOGw_Ywg",
          |    "name": "COMP0031-PlantBot",
          |    "full_name": "Aashvin/COMP0031-PlantBot",
          |    "private": false,
          |    "owner": {
          |      "login": "Aashvin",
          |      "id": 55795472,
          |      "node_id": "MDQ6VXNlcjU1Nzk1NDcy",
          |      "avatar_url": "https://avatars.githubusercontent.com/u/55795472?v=4",
          |      "gravatar_id": "",
          |      "url": "https://api.github.com/users/Aashvin",
          |      "html_url": "https://github.com/Aashvin",
          |      "followers_url": "https://api.github.com/users/Aashvin/followers",
          |      "following_url": "https://api.github.com/users/Aashvin/following{/other_user}",
          |      "gists_url": "https://api.github.com/users/Aashvin/gists{/gist_id}",
          |      "starred_url": "https://api.github.com/users/Aashvin/starred{/owner}{/repo}",
          |      "subscriptions_url": "https://api.github.com/users/Aashvin/subscriptions",
          |      "organizations_url": "https://api.github.com/users/Aashvin/orgs",
          |      "repos_url": "https://api.github.com/users/Aashvin/repos",
          |      "events_url": "https://api.github.com/users/Aashvin/events{/privacy}",
          |      "received_events_url": "https://api.github.com/users/Aashvin/received_events",
          |      "type": "User",
          |      "site_admin": false
          |    },
          |    "html_url": "https://github.com/Aashvin/COMP0031-PlantBot",
          |    "description": null,
          |    "fork": false,
          |    "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot",
          |    "forks_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/forks",
          |    "keys_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/keys{/key_id}",
          |    "collaborators_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/collaborators{/collaborator}",
          |    "teams_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/teams",
          |    "hooks_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/hooks",
          |    "issue_events_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/issues/events{/number}",
          |    "events_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/events",
          |    "assignees_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/assignees{/user}",
          |    "branches_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/branches{/branch}",
          |    "tags_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/tags",
          |    "blobs_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs{/sha}",
          |    "git_tags_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/tags{/sha}",
          |    "git_refs_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/refs{/sha}",
          |    "trees_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/trees{/sha}",
          |    "statuses_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/statuses/{sha}",
          |    "languages_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/languages",
          |    "stargazers_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/stargazers",
          |    "contributors_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contributors",
          |    "subscribers_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/subscribers",
          |    "subscription_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/subscription",
          |    "commits_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/commits{/sha}",
          |    "git_commits_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/commits{/sha}",
          |    "comments_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/comments{/number}",
          |    "issue_comment_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/issues/comments{/number}",
          |    "contents_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/{+path}",
          |    "compare_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/compare/{base}...{head}",
          |    "merges_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/merges",
          |    "archive_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/{archive_format}{/ref}",
          |    "downloads_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/downloads",
          |    "issues_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/issues{/number}",
          |    "pulls_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/pulls{/number}",
          |    "milestones_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/milestones{/number}",
          |    "notifications_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/notifications{?since,all,participating}",
          |    "labels_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/labels{/name}",
          |    "releases_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/releases{/id}",
          |    "deployments_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/deployments",
          |    "created_at": "2022-01-31T13:47:34Z",
          |    "updated_at": "2022-03-26T10:50:25Z",
          |    "pushed_at": "2022-03-30T06:03:42Z",
          |    "git_url": "git://github.com/Aashvin/COMP0031-PlantBot.git",
          |    "ssh_url": "git@github.com:Aashvin/COMP0031-PlantBot.git",
          |    "clone_url": "https://github.com/Aashvin/COMP0031-PlantBot.git",
          |    "svn_url": "https://github.com/Aashvin/COMP0031-PlantBot",
          |    "homepage": null,
          |    "size": 1577,
          |    "stargazers_count": 0,
          |    "watchers_count": 0,
          |    "language": "Python",
          |    "has_issues": true,
          |    "has_projects": true,
          |    "has_downloads": true,
          |    "has_wiki": true,
          |    "has_pages": false,
          |    "has_discussions": false,
          |    "forks_count": 0,
          |    "mirror_url": null,
          |    "archived": false,
          |    "disabled": false,
          |    "open_issues_count": 0,
          |    "license": null,
          |    "allow_forking": true,
          |    "is_template": false,
          |    "web_commit_signoff_required": false,
          |    "topics": [
          |
          |    ],
          |    "visibility": "public",
          |    "forks": 0,
          |    "open_issues": 0,
          |    "watchers": 0,
          |    "default_branch": "main"
          |  }
          |]""".stripMargin

    val repoContentsResponse: String = """[
                                         |  {
                                         |    "name": ".gitignore",
                                         |    "path": ".gitignore",
                                         |    "sha": "d435107f280a6ee82cb6df46965a25b5c68b965f",
                                         |    "size": 54,
                                         |    "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/.gitignore?ref=main",
                                         |    "html_url": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/.gitignore",
                                         |    "git_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/d435107f280a6ee82cb6df46965a25b5c68b965f",
                                         |    "download_url": "https://raw.githubusercontent.com/Aashvin/COMP0031-PlantBot/main/.gitignore",
                                         |    "type": "file",
                                         |    "_links": {
                                         |      "self": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/.gitignore?ref=main",
                                         |      "git": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/d435107f280a6ee82cb6df46965a25b5c68b965f",
                                         |      "html": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/.gitignore"
                                         |    }
                                         |  },
                                         |  {
                                         |    "name": "README.md",
                                         |    "path": "README.md",
                                         |    "sha": "4d6d2eb5aee8ff0bb2ce629347099cb648fbf9d5",
                                         |    "size": 5796,
                                         |    "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/README.md?ref=main",
                                         |    "html_url": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/README.md",
                                         |    "git_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/4d6d2eb5aee8ff0bb2ce629347099cb648fbf9d5",
                                         |    "download_url": "https://raw.githubusercontent.com/Aashvin/COMP0031-PlantBot/main/README.md",
                                         |    "type": "file",
                                         |    "_links": {
                                         |      "self": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/README.md?ref=main",
                                         |      "git": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/4d6d2eb5aee8ff0bb2ce629347099cb648fbf9d5",
                                         |      "html": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/README.md"
                                         |    }
                                         |  },
                                         |  {
                                         |    "name": "plantbot",
                                         |    "path": "plantbot",
                                         |    "sha": "d8fb8bf1e7ec233977962885515cf848ef7cba6c",
                                         |    "size": 0,
                                         |    "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/plantbot?ref=main",
                                         |    "html_url": "https://github.com/Aashvin/COMP0031-PlantBot/tree/main/plantbot",
                                         |    "git_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/trees/d8fb8bf1e7ec233977962885515cf848ef7cba6c",
                                         |    "download_url": null,
                                         |    "type": "dir",
                                         |    "_links": {
                                         |      "self": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/plantbot?ref=main",
                                         |      "git": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/trees/d8fb8bf1e7ec233977962885515cf848ef7cba6c",
                                         |      "html": "https://github.com/Aashvin/COMP0031-PlantBot/tree/main/plantbot"
                                         |    }
                                         |  },
                                         |  {
                                         |    "name": "yolo-configs",
                                         |    "path": "yolo-configs",
                                         |    "sha": "ca1478da2205570f6485d225e1b3d3a4d77e01c7",
                                         |    "size": 0,
                                         |    "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/yolo-configs?ref=main",
                                         |    "html_url": "https://github.com/Aashvin/COMP0031-PlantBot/tree/main/yolo-configs",
                                         |    "git_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/trees/ca1478da2205570f6485d225e1b3d3a4d77e01c7",
                                         |    "download_url": null,
                                         |    "type": "dir",
                                         |    "_links": {
                                         |      "self": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/yolo-configs?ref=main",
                                         |      "git": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/trees/ca1478da2205570f6485d225e1b3d3a4d77e01c7",
                                         |      "html": "https://github.com/Aashvin/COMP0031-PlantBot/tree/main/yolo-configs"
                                         |    }
                                         |  }
                                         |]""".stripMargin

    val repoFileResponse: String = """{
                                     |  "name": ".gitignore",
                                     |  "path": ".gitignore",
                                     |  "sha": "d435107f280a6ee82cb6df46965a25b5c68b965f",
                                     |  "size": 54,
                                     |  "url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/.gitignore?ref=main",
                                     |  "html_url": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/.gitignore",
                                     |  "git_url": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/d435107f280a6ee82cb6df46965a25b5c68b965f",
                                     |  "download_url": "https://raw.githubusercontent.com/Aashvin/COMP0031-PlantBot/main/.gitignore",
                                     |  "type": "file",
                                     |  "content": "KiovX19weWNhY2hlX18KKiovLnZzY29kZQoqKi5weWMKKiovLmlweW5iX2No\nZWNrcG9pbnRz\n",
                                     |  "encoding": "base64",
                                     |  "_links": {
                                     |    "self": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/contents/.gitignore?ref=main",
                                     |    "git": "https://api.github.com/repos/Aashvin/COMP0031-PlantBot/git/blobs/d435107f280a6ee82cb6df46965a25b5c68b965f",
                                     |    "html": "https://github.com/Aashvin/COMP0031-PlantBot/blob/main/.gitignore"
                                     |  }
                                     |}""".stripMargin
}
